[package]
name = "rok"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
itertools = "0.11.0"
log = "0.4.19"
# TODO: turn on "simd" feature. Failing to build on 20230715
polars = { version = "0.30.0", features = ["performant", "parquet", "dtype-categorical"] }
rustyline = "12.0.0"
